=== mborne/node-postgis-helper/docs/Table.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Table",
  "description": "Describe an SQL table",
  "type": "object",
  "required": [
    "name",
    "columns"
  ],
  "properties": {
    "schema": {
      "type": "string",
      "title": "Schema",
      "description": "The name of the schema containing the table"
    },
    "name": {
      "type": "string",
      "title": "Name",
      "description": "The name of the table"
    },
    "title": {
      "type": "string",
      "title": "Title",
      "description": "The display name of the table"
    },
    "description": {
      "type": "string",
      "title": "Description",
      "description": "The description of the table"
    },
    "primaryKey": {
      "type": "array",
      "title": "Primary keys",
      "description": "The column(s) identifying rows",
      "items": {
        "type": "string"
      }
    },
    "foreignKeys": {
      "type": "array",
      "title": "Foreign keys",
      "items": {
        "$ref": "#/definitions/ForeignKey"
      }
    },
    "columns": {
      "type": "array",
      "title": "Columns",
      "description": "Columns definition",
      "items": {
        "$ref": "#/definitions/Column"
      }
    }
  },
  "definitions": {
    "Column": {
      "type": "object",
      "title": "Column",
      "required": [
        "name",
        "type"
      ],
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "description": "The name of the table"
        },
        "title": {
          "type": "string",
          "title": "Title",
          "description": "The display name of the table"
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "The description of the table"
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Native SQL type"
        },
        "required": {
          "type": "boolean",
          "title": "Required",
          "description": "Indicates if value is required (opposite of nullable)",
          "default": false
        }
      }
    },
    "ForeignKey": {
      "type": "object",
      "title": "Foreign key",
      "description": "Describe a reference to another table",
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "description": "The name of the constraints"
        },
        "columns": {
          "type": "array",
          "title": "Column",
          "description": "Source table columns",
          "items": {
            "type": "string"
          }
        },
        "target": {
          "type": "object",
          "title": "Target",
          "description": "The target of the foreign key",
          "properties": {
            "schema": {
              "type": "string",
              "title": "Target schema"
            },
            "name": {
              "type": "string",
              "title": "Target table"
            },
            "columns": {
              "type": "array",
              "title": "Target columns",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}

=== mborne/node-postgis-helper/test/DATA/adminexpress/region.json
{
  "name": "region",
  "title": "RÃ©gion",
  "primaryKey": [
    "id"
  ],
  "columns": [
    {
      "name": "id",
      "type": "text"
    },
    {
      "name": "nom_reg",
      "type": "text"
    },
    {
      "name": "nom_reg_m",
      "type": "text"
    },
    {
      "name": "insee_reg",
      "type": "text",
      "unique": true
    },
    {
      "name": "chf_reg",
      "type": "text"
    },
    {
      "name": "geom",
      "type": "geometry(MultiPolygon,4326)",
      "required": true
    }
  ]
}

=== mborne/node-postgis-helper/test/helpers/expected/user_ext.json
{
  "name": "user_ext",
  "primaryKey": [
    "id"
  ],
  "foreignKeys": [],
  "columns": [
    {
      "name": "id",
      "title": "Identifier",
      "type": "serial",
      "required": false,
      "unique": false,
      "reference": null
    },
    {
      "name": "username",
      "title": "Username",
      "type": "text",
      "required": false,
      "unique": false,
      "reference": null
    },
    {
      "name": "birthdate",
      "title": "Birthdate",
      "type": "date",
      "required": false,
      "unique": false,
      "reference": null
    },
    {
      "name": "is_admin",
      "title": "Administrator?",
      "type": "boolean",
      "required": false,
      "unique": false,
      "reference": null,
      "default": false
    },
    {
      "name": "location",
      "title": "Location",
      "type": "geometry(Point,4326)",
      "required": false,
      "unique": false,
      "reference": null
    },
    {
      "name": "extra",
      "title": "Extra",
      "type": "text",
      "required": false,
      "unique": false,
      "reference": null
    }
  ]
}

=== mborne/node-postgis-helper/test/DATA/sample/building_owner.json
{
  "name": "building_owner",
  "primaryKey": [
    "id"
  ],
  "foreignKeys": [
    {
      "name": "building_owner_building_id_fkey",
      "columns": [
        "building_id",
        "building_version"
      ],
      "target": {
        "schema": "sample",
        "name": "building_h",
        "columns": [
          "id",
          "version"
        ]
      }
    },
    {
      "name": "building_owner_owner_id_fkey",
      "columns": [
        "owner_id"
      ],
      "target": {
        "schema": "sample",
        "name": "user",
        "columns": [
          "id"
        ]
      }
    }
  ],
  "columns": [
    {
      "name": "id",
      "type": "integer",
      "required": true
    },
    {
      "name": "building_id",
      "type": "uuid",
      "required": false
    },
    {
      "name": "building_version",
      "type": "integer",
      "required": false
    },
    {
      "name": "owner_id",
      "type": "integer",
      "required": false
    }
  ]
}

=== mborne/node-postgis-helper/test/DATA/adminexpress/departement.json
{
  "name": "departement",
  "title": "DÃ©partement",
  "primaryKey": [
    "id"
  ],
  "columns": [
    {
      "name": "id",
      "type": "text"
    },
    {
      "name": "nom_dep",
      "type": "text"
    },
    {
      "name": "nom_dep_m",
      "type": "text"
    },
    {
      "name": "insee_dep",
      "type": "text",
      "unique": true
    },
    {
      "name": "insee_reg",
      "type": "text",
      "reference": {
        "schema": "adminexpress",
        "name": "region",
        "column": "insee_reg"
      }
    },
    {
      "name": "chf_dep",
      "type": "text"
    },
    {
      "name": "geom",
      "type": "geometry(MultiPolygon,4326)",
      "required": true
    }
  ]
}

=== mborne/node-postgis-helper/test/DATA/adminexpress/commune.json
{
  "name": "commune",
  "title": "Commune",
  "primaryKey": [
    "id"
  ],
  "columns": [
    {
      "name": "id",
      "type": "text"
    },
    {
      "name": "type",
      "type": "text"
    },
    {
      "name": "nom_com",
      "type": "text"
    },
    {
      "name": "nom_com_m",
      "type": "text"
    },
    {
      "name": "insee_com",
      "type": "text",
      "unique": true
    },
    {
      "name": "statut",
      "type": "text"
    },
    {
      "name": "population",
      "type": "numeric(8,0)"
    },
    {
      "name": "insee_arr",
      "type": "text"
    },
    {
      "name": "nom_dep",
      "type": "text"
    },
    {
      "name": "insee_dep",
      "type": "text",
      "reference": "adminexpress.departement(insee_dep)"
    },
    {
      "name": "nom_reg",
      "type": "text"
    },
    {
      "name": "insee_reg",
      "type": "text"
    },
    {
      "name": "code_epci",
      "type": "text"
    },
    {
      "name": "geom",
      "type": "geometry(MultiPolygon,4326)",
      "required": true
    }
  ]
}
